### ISSUE TITLE
Undefined method parse

### ISSUE THREAD

**Issue by alinlacea** [kiyoto/fluent-plugin-grok-parser#4]
Hello,

I recently installed your plugin for fluentd. After configuring as below,
```
<source>
    type tail
    path /var/log/supervisor/statsApi_1.stdout.log
    format grok
    grok_pattern %{TIMESTAMP_ISO8601:timestamp}:%{USER:module}:%{USER:lib} - %{DATA:message}
    tag vt4.api.stats
  </source>
```
I receive the following errors in td-agent.log:
```
error="undefined method `parse' for #<Fluent::TextParser::GrokParser:0x002b2e47067700>"
``` 

Am I missing something here? The patterns seem to expand according to the same log ( "Expanded the pattern"...).

Thanks

**Comment by kiyoto** [comment]
What version of Fluentd do you use? You can get this via `fluentd --version`.

**Comment by alinlacea** [comment]
1. I actually td-agent with version td-agent 0.10.58
2. I installed the plugin via the sudo /usr/sbin/td-agent-gem install fluent-plugin-grok-parser command.

**Comment by kiyoto** [comment]
Thanks! Will check later this week =)

**Comment by yedeng** [comment]
I have the similar issue. When I setup grok expression to parse raw logs, I got some error message like: error="undefined method `parse' for #<Fluent::TextParser::GrokParser:0x007f6b1aaeb0a0>"

My environment:
1. I also use td-agent 0.10.58 on ubuntu 14.04(trusty).
2. I also installed the grok plugin with td-agent-gem: 
> sudo td-agent-gem install fluent-plugin-grok-parser
Fetching: fluent-plugin-grok-parser-0.0.1.gem (100%)
Successfully installed fluent-plugin-grok-parser-0.0.1
… … 

I am sure my grok expression is correct because I can bypass the error by expanding my grok expression and using low-level regular expression directly.

I mean, instead of use:
format grok
grok_pattern my_grok_expression 
I use:
format expanded_low_level_regular_expression

I get expanded_low_level_regular_expression by checking /var/log/td-agent/td-agent.log.

**Comment by kiyoto** [comment]
Hi @alinlacea and @yedeng-

Sorry for the late response. This was already addressed in the master (essentially, my old code wasn't compatible with the new API v0.10.58 and up). Can you try reinstalling fluent-plugin-grok-parser and report if the issue persists?

**Comment by kiyoto** [comment]
Ping @alinlacea and @yedeng ?

**Comment by yedeng** [comment]
Sorry for the late reply. I was using my expanded low-level regular expression (very verbose expression).

To test your patch, I reinstalled fluent-plugin-grok-parser. When I restarted tg-agent, its log shows that both v0.0.2 and v0.0.1 are loaded. Thus, I manually uninstalled v0.0.1. Now, I am using grok pattern to parse logs, and I find it works correctly.

I have one more suggestion. Maybe, in your doc, you may want to explain how to optionally define field types with your plugin. Based on my tests, optional field types should be defined by adding a line like "types user_id:integer,paid:bool,paid_usd_amount:float" (based on: http://docs.fluentd.org/articles/in_tail). The optional types cannot be defined by the logstash-grok way "{NUMBER:num:int}" (based on: http://logstash.net/docs/1.4.2/filters/grok).

**Comment by kiyoto** [comment]
@yedeng thanks for your comment. i will 1. update my doc and 2. hopefully address it in the future in #5
